### ISSUE TITLE
Update docs to require Gradle 4.9

### ISSUE THREAD

**Issue by jimmywan** [hellofresh/deblibs-gradle-plugin#41]
### Expected behavior
Expect this to work with Gradle 4.3

### Actual behavior
```
Creating deblibs tasks...


FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.tasks.TaskContainer.register(Ljava/lang/String;Ljava/lang/Class;Lorg/gradle/api/Action;)Lorg/gradle/api/tasks/TaskProvider;
```

### Steps to reproduce the behavior
 - Install gradle 4.3
 - run `./gradlew --stacktrace --info createSlackMessage`

From the gradle docs, it looks like this endpoint was added in 4.9:
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskContainer.html#register-java.lang.String-org.gradle.api.Action-

**Comment by eyedol** [comment]
@jimmywan thanks for reporting. We will look into this
